### PR TITLE
Better library

### PR DESCRIPTION
**Pull request by Nyan11**
Test if the CI works

### CODE REVIEW

**Comment by labordep** [comment]
@Nyan11 is it ok to merge? (ignore P13 tests)

**Comment by Nyan11** [comment]
Not yet.

When i load this branch i have AnObsoletePyramidSpCodeObjectInteractionModel added i do not know why.
I'm investigating.

**Comment by labordep** [comment]
This PR is related to #168

**Review by labordep — APPROVED** [review]

**Comment by labordep** [comment]
@Nyan11 can you add a section in the readme with an illustration? Thanks :)

**Pull request merged**
