### PR TITLE
Stash serializer

### PR DESCRIPTION
**Pull request by Nyan11**

### CODE REVIEW

**Comment by Nyan11** [comment]
To merge after: https://github.com/OpenSmock/Pyramid/pull/185

**Comment by Nyan11** [comment]
First merge this: https://github.com/OpenSmock/Bloc-Serialization/pull/17

**Comment by labordep** [comment]
Merge #185 done.

**Comment by labordep** [comment]
@Nyan11, serializations tests are KO: `Instance of Array did not understand #materializeAsBlElement`

**Comment by Nyan11** [comment]
> ~To merge after: [OpenSmock/Bloc-Serialization#17](https://github.com/OpenSmock/Bloc-Serialization/pull/17)~ To merge after: [OpenSmock/Bloc-Serialization#19](https://github.com/OpenSmock/Bloc-Serialization/pull/19)

Do that before: To merge after: https://github.com/OpenSmock/Bloc-Serialization/pull/19

**Comment by Nyan11** [comment]
> @Nyan11, serializations tests are KO: `Instance of Array did not understand #materializeAsBlElement`

Do that before: To merge after: https://github.com/OpenSmock/Bloc-Serialization/pull/19

**Comment by labordep** [comment]
Ok done.

**Comment by labordep** [comment]
Related to #14

**Pull request merged**
