### PR TITLE
Add the possibility of tags in package selection while saving

### PR DESCRIPTION
**Pull request by Nyan11**

### CODE REVIEW

**Review by labordep — CHANGES_REQUESTED** [review]
@Nyan11 there are a lot of formatting changes, do you code with Pharo 11 ?
We have a similar problem in PR for molecule, do you know anything about that ?

**Comment by labordep** [comment]
@Nyan11 same problem than the other PR : 
image

This is a huge numer of changes !! and I cannot read easily your real changes....

**Comment by Nyan11** [comment]
On windows

**Comment by labordep** [comment]
Oh shit, it's appears that P12 have a different format for files. Can you set a PR using P11 to be sure ?

**Comment by Nyan11** [comment]
The method category used to be a string in Pharo 11 and less. It changed has a symbol (with a #) in pharo 12

**Comment by Nyan11** [comment]
The method category used to be a string in Pharo 11 and less. It changed has a symbol (with a #) in pharo 12

**Comment by Nyan11** [comment]
> > Oh shit, it's appears that P12 have a different format for files. Can you set a PR using P11 to be sure ?
> 
> I will try

https://github.com/OpenSmock/Pyramid/pull/96

I create a Pull request from Pharo 11 and i do not have the issue

**Comment by Nyan11** [comment]
> I have the explanation :
> 
> ```
> I just wanted to let people who are using Pharo12 that they might notice some changes while exporting their code to github now.
> 
> We are introducing a TonelV3 format. The goals are to:
> - Follow the spec that was agreed upon because currently we have symbols instead of strings in some places and that made it incompatible with Gemstone or Vast 
> - Add missing informations. This is because in Pharo we have packages and tags but the only thing exported is the category. So reading the categories was ambiguous and relied on some heuristic. Loading the same class in two pharo image could load the class in different packages depending on the state of the image. 
> - We want to add meta data for new features (not yet done). For example there is a new feature to rename a class and keep the old name as a deprecated alias for a while. We would like to be able to declare those info in the fluid class definition and in the Tonel format.
> 
> The new format still exports the category (but there is a setting to not export it) to stay backward compatible for now. 
> Using the Tonel paser to read classes that were exported before Pharo 12 can have some difficulties to manage the tags, but the TonelReader class that is used by Iceberg knows how to resolve all of those problem to ensure the classes are in the right packages and in the right classes!
> ```
> 
> So don't use Pharo 12 for this work. Can you re send your modifications with P11 ? Thanks.

Yes i will try to copy the modification on a Pharo 11 VM

**Comment by Nyan11** [comment]
New pull request : https://github.com/OpenSmock/Pyramid/pull/98

**Pull request closed without merging**
