### PR TITLE
83 write a bl space extensions to edit a space into pyramid

### PR DESCRIPTION
**Pull request by labordep**
Work on #83

### CODE REVIEW

**Comment by labordep** [comment]
@Nyan11 can you test and review this feature before merge ? thanks :)

**Comment by Nyan11** [comment]
Ok i will look

**Review by Nyan11 — COMMENTED** [review]
I found a bug.
When i spam F12 shortcut on a space i managed to open multiple instances of Pyramid.

**Comment by labordep** [comment]
Thanks for your feedback :-) 
I will modify to start only on action fork for each space.

**Pull request merged**
